### ISSUE TITLE
Shapeshift

### ISSUE THREAD

**Issue by airanp** [seblindfors/ConsolePort#10]
I am loving the addon.  After getting into FFXIV I decided to check this out and it is working wonderfully.  The only issue I am having right now is when I switch forms on my druid it does not dynamically switch the key bindings for the addon.  Whatever form I am in after a /reload or upon logging in is the action bar that gets the key bindings.  I am currently using ElvUI, not sure if that matters much over the default UI.

**Comment by seblindfors** [comment]
It's a problem with ElvUI. There are other issues with ElvUI, too, such as the raid cursor not working with the raid frames. How customized are your bindings?

**Comment by airanp** [comment]
1-6 are normal.  7-= are changed to other letters.  I tried to put the
bindings back to default but it was the same result.  The only thing that
worked was reloading the ui after every shape shift.  I'm going to play
around with it some more.  I am loving playing with the controller, its
like a whole new game.  Just need to get a ui that works flawless with it.

**Comment by seblindfors** [comment]
Which version are you using btw? The new binding system does not use the system you describe anymore.

**Comment by airanp** [comment]
Not at the house but the latest one that is on curse.  The bindings are a b
x y lt lb and so one.  And it goes to the f keys through xpadder.

**Comment by seblindfors** [comment]
You can try this and see if it solves your issue:
1. Disable ElvUI temporarily.
2. Log in with ConsolePort running and reset your bindings to default.
3. Rebind the action bars as you want them to be.
4. Re-enable ElvUI.

If that doesn't work, I'll do some testing on my druid later and see if I can reproduce your problem.

**Comment by airanp** [comment]
Tried disabling ElvUI and logging in with ConsolePort running.  Worked just
fine.  I tried TukUI, which is made by the same people but is pretty much
just a minimalist reskin of the blizzard UI without any customization in
the background and it worked just fine.  No idea what they are doing with
ElvUI, but however they are managing their action bars is not working with
ConsolePort.  Or I am just missing a vital check mark in the settings
somewhere.

On Tue, Dec 22, 2015 at 3:17 AM, Sebastian Lindfors <
notifications@github.com> wrote:

> You can try this and see if it solves your issue:
> 1. Disable ElvUI temporarily.
> 2. Log in with ConsolePort running and reset your bindings to default.
> 3. Rebind the action bars as you want them to be.
> 4. Re-enable ElvUI.
>
> If that doesn't work, I'll do some testing on my druid later and see if I
> can reproduce your problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/seblindfors/ConsolePort/issues/10#issuecomment-166550798>
> .
>



-- 
Airan W. Parsons

**Comment by seblindfors** [comment]
Weird, but I'm not completely surprised. ElvUI also does some strange under-the-hood manipulation of the "secure environment", which causes a complete meltdown if you try to use their raid frames with the raid cursor from ConsolePort. I guess it was never really an issue for them, because the way ConsolePort handles and manipulates the interface is kind of unique.

The management of bindings in ConsolePort is built on the assumption that any custom action bar addon is using orthodox methods to host actions. Developers have a bit of freedom with how they approach action bars, but the best and most robust way is using the same approach as Blizzard. Bartender is one such addon. ButtonForge is not.

If you REALLY want to use ElvUI, you might want to try binding directly on to the bars. This could potentially solve your issue, but if I'm not mistaken, it will render those bindings useless whenever ElvUI is disabled. Here's a clip of how to do it:
https://youtu.be/EkAVV0lu18o?t=45s

**Comment by seblindfors** [comment]
I've located the issue of this bug and it is indeed caused by ElvUI. For whatever reason, they are repressing the default Blizzard action bar from updating. This is not a necessary behaviour to implement, since Bartender4 does not force the default bars to stop updating. 

I think the reason the developers of ElvUI did this was to add some very minor optimization, since they probably assumed nobody would be using the action page value from the default bar anyway. ConsolePort does not use the default action bar, but it uses the wrapped bindings provided by Blizzard. Those bindings rely on a correct action page value from the default bar.

I've reported the issue(s) to the ElvUI developers.

**Comment by airanp** [comment]
For now I am content just enjoying the game with a DS4 controller.  Even
though I really like elvui and all it brings to the table, I can tolerate
tukui and it's minimalist look if that is what it takes to fully enjoy the
game from the couch.  Thanks again for the responses and for the amazing
add-on

On Thu, Dec 24, 2015 at 2:06 AM, Sebastian Lindfors <
notifications@github.com> wrote:

> I've located the issue of this bug and it is indeed caused by ElvUI. For
> whatever reason, they are repressing the default Blizzard action bar from
> updating. This is not a necessary behaviour to implement, since Bartender4
> does not force the default bars to stop updating.
>
> I think the reason the developers of ElvUI did this was to add some very
> minor optimization, since they probably assumed nobody would be using the
> action page value from the default bar anyway. ConsolePort does not use the
> default action bar, but it uses the wrapped bindings provided by Blizzard.
> Those bindings rely on a correct action page value from the default bar.
>
> I've reported the issue(s) to the ElvUI developers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/seblindfors/ConsolePort/issues/10#issuecomment-167058717>
> .
>



-- 
Airan W. Parsons

**Comment by seblindfors** [comment]
You're welcome! Good luck and have fun! :wink:
