### ISSUE TITLE
RT combinations sometimes stop working

### ISSUE THREAD

**Issue by Baldrs** [seblindfors/ConsolePort#16]
I'm using console port with steam controller, bindings are provided by steam in big picture mode. 

While controller is intact and other buttons are generally fine, including LT+RT modified actions, sometimes RT as exclusive modifier stops working and interface restart does not help. I use bartender 4 to modify panel layout. 

Also I have noticed if spell bound to Y procs, I cannot start combat with it, at first I need to enter combat with another spell.

**Comment by seblindfors** [comment]
The RT-issue you speak of doesn't have to do with the addon, since the addon only responds to the controller. It can't simply omit the input of a modifier. Something is wrong either with your controller or the profile, although I never ran into this issue with the official template. 

I don't understand your second issue in the sense that there's nothing special about Y in particular. You'll have to provide information about what it's bound to, in what situation it happens and whether you're using Y as any of the interface cursor inputs.

**Comment by Baldrs** [comment]
Second issue happens to different keys, for some reason they are unusable from outside of combat mode(until I enter combat with any different skill)

Where can I find an official template for a steam controller btw? maybe I have just configured it wrong way

**Comment by seblindfors** [comment]
Are you using a custom interface?

Here's the profile anyway:
http://forums.consoleport.net/index.php?action=dlattach;topic=6.0;attach=5

**Comment by Baldrs** [comment]
Just bartender4 for panels. Also maybe worth mentioning that I'm using wine to run wow, maybe that's the problem?

**Comment by Baldrs** [comment]
Tried disabling bartender, seems to be cause for both problems.
