### ISSUE TITLE
Enhancement suggestion: Window toggling

### ISSUE THREAD

**Issue by crohde7707** [seblindfors/ConsolePort#26]
First off, great job on this addon. I have been keeping an eye on this, since we started right around the same time on this type of addon. I want to contribute some of the features that I integrated into my addon, since you have the graphical expertise :)

I would suggest that when you have a merchant/bank frame open, and your bag open, having a quick toggle to jump between the two. Haven't dug into how you are tracking the buttons in the frame, but it would definitely provide a more fluent experience when traversing across the screen.

If you are open to it, I will gladly contribute :) Putting mine on hold for when they announce legacy servers

**Comment by seblindfors** [comment]
Tracking is done through a recursive process that gathers all nodes on screen and checks each node's distance to the current focus in the horizontal and vertical planes. There's not really any tracking of individual frames going on, rather the frames act as triggers for the cursor to be engaged. 

I'd be interested to see what you're doing and whether it's a plausible addition, but the interface management is already very convoluted in that regard because it's completely dynamic. 

On another note, I'm already in the process of creating my own interface replacement, which will make these things way easier anyway.
