### ISSUE TITLE
Void Torrent and Console Port

### ISSUE THREAD

**Issue by thebaaj666** [seblindfors/ConsolePort#32]
After 7.2 dropped, I can no longer cast void Torrent while using Console Port. The game completely crashes any time void Torrent is used. I've been able to cast the spell when not using Console port, so I assume it has something to do with the way the add-on 'retrieves' the skill from the wow memory. Any help would be appreciated.

**Comment by seblindfors** [comment]
This is likely a game bug that has gone undetected with the release of 7.2 and not caused by ConsolePort specifically. ConsolePort does no such thing as 'retrieving the spell from memory'; it simply uses built in API to update the textures, cooldowns and counters on your action bar. There is no recurse in that lexical scope, so the addon cannot cause a game freeze or crash by memory leak.

**Comment by thebaaj666** [comment]
Thanks for the reply! I'll make an in game report.
