### ISSUE TITLE
add possibility to remove / rescale keybind symbols

### ISSUE THREAD

**Issue by marcjhayden** [seblindfors/ConsolePort#92]
currently, the shortcut symbols take up half of the skills (at least if you are using elvui + luckyone, classic era). It would be great to have:
- the ability to scale the shortcut symbols
- option to disable modifier symbols,
- option to disable all symbols all together. 

I tried disabling the keybind text via ElvUI but that has no effect.

![image](https://github.com/seblindfors/ConsolePort/assets/14203506/99c27f87-7e02-459e-8da4-d085964ccb1a)

**Comment by seblindfors** [comment]
This is some effect caused by one of your addons. The default size on action bars scales to roughly 12px per symbol, and three symbols can fit horizontally without problem. You can disable all symbols if you want, using `/cp disableHotkeyRendering true` or Interface > Bindings > Disable Hotkey Rendering

**Comment by marcjhayden** [comment]
thanks, I did not find that setting earlier!
